apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-manifest-demo
  labels:
    app: single-manifest-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-manifest-demo
  template:
    metadata:
      labels:
        app: single-manifest-demo
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Always

